document.write("<div style='z-index: 1000; border: 1px solid #F7941D; background: #FEEFDA; text-align: center; clear: both; height: 75px; position: relative;'>");
document.write("<div style='position: absolute; right: 3px; top: 3px; font-family: courier new; font-weight: bold;'>");
document.write("<a href='#' onclick='javascript:this.parentNode.parentNode.style.display='none'; return false;'>");
document.write("<img src='http:\/\/www.ie6nomore.com\/files\/theme\/ie6nomore-cornerx.jpg' style='border: none;' alt='Close this notice'\/>");
document.write("<\/a>");
document.write("<\/div>");
document.write("<div style='width: 640px; margin: 0 auto; text-align: left; padding: 0; overflow: hidden; color: black;'>");
document.write("<div style='width: 75px; float: left;'>");
document.write("<img src='http:\/\/www.ie6nomore.com\/files\/theme\/ie6nomore-warning.jpg' alt='Warning!'\/>");
document.write("<\/div>");
document.write("<div style='width: 275px; float: left; font-family: Arial, sans-serif;'>");
document.write("<div style='font-size: 14px; font-weight: bold; margin-top: 12px;'>あなたは旧式ブラウザをご利用中です<\/div>");
document.write("<div style='font-size: 12px; margin-top: 6px; line-height: 12px;'>このウェブサイトを快適に閲覧するにはブラウザをアップグレードしてください。");
document.write("<\/div>");
document.write("<\/div>");
document.write("<div style='width: 75px; float: left;'>");
document.write("<a href='http:\/\/www.mozilla.jp' target='_blank'>");
document.write("<img src='http:\/\/www.ie6nomore.com\/files\/theme\/ie6nomore-firefox.jpg' style='border: none;' alt='Get Firefox 3.5'\/>");
document.write("<\/a>");
document.write("<\/div>");
document.write("<div style='width: 75px; float: left;'>");
document.write("<a href='http:\/\/www.microsoft.com\/downloads\/details.aspx?FamilyID=341c2ad5-8c3d-4347-8c03-08cdecd8852b&DisplayLang=ja' target='_blank'>");
document.write("<img src='http:\/\/www.ie6nomore.com\/files\/theme\/ie6nomore-ie8.jpg' style='border: none;' alt='Get Internet Explorer 8'\/>");
document.write("<\/a>");
document.write("<\/div>");
document.write("<div style='width: 73px; float: left;'>");
document.write("<a href='http:\/\/www.apple.com\/jp\/safari\/download\/' target='_blank'>");
document.write("<img src='http:\/\/www.ie6nomore.com\/files\/theme\/ie6nomore-safari.jpg' style='border: none;' alt='Get Safari 4'\/>");
document.write("<\/a>");
document.write("<\/div>");
document.write("<div style='float: left;'>");
document.write("<a href='http:\/\/www.google.com\/chrome?hl=ja' target='_blank'>");
document.write("<img src='http:\/\/www.ie6nomore.com\/files\/theme\/ie6nomore-chrome.jpg' style='border: none;' alt='Get Google Chrome'\/>");
document.write("<\/a>");
document.write("<\/div>");
document.write("<\/div>");
document.write("<\/div>");
document.write("");

